AWSTemplateFormatVersion: "2010-09-09"
Description:
  無料の範囲内でEC2インスタンスを構築するためのテンプレートです。そのため、コンピューティング性能（AMI,インスタンスタイプ）は最少スペックで構成。
  なお、サーバー種別はWebサーバーを想定しています。

Metadata:
  AWS::CloudFormation::Interface:
    # 各種パラメータ（コンソール画面からの入力用）
    ParameterGroups:
      - Label:
          default: Name Prefix
        Parameters:
          - CompanyPrefix
          - PJPrefix
      - Label:
          default: EC2Instance Configuration
        Parameters:
          - KeyPairName
          - EC2InstanceName
          - EC2InstanceAMI
          - EC2InstanceInstanceType
          - EC2InstanceVolumeType
          - EC2InstanceVolumeSize
          - SSHAccessSourceIP
    # 各種パラメータのエイリアス
    ParameterLabels:
      KeyPairName:
        default: KeyPairName
      EC2InstanceName:
        default: EC2 Name
      EC2InstanceAMI:
        default: EC2 AMI
      EC2InstanceInstanceType:
        default: EC2 InstanceType
      EC2InstanceVolumeType:
        default: EC2 VolumeType
      EC2InstanceVolumeSize:
        default: EC2 VolumeSize
      SSHAccessSourceIP:
        default: SSH AccessSourceIP

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  CompanyPrefix:
    Type: String
  PJPrefix:
    Type: String
  
  # EC2Instance
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "key"
  EC2InstanceName:
    Type: String
    Default: web
  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EC2InstanceInstanceType:
    Type: String
    Default: t2.micro
  EC2InstanceVolumeType:
    Type: String
    Default: gp2
  EC2InstanceVolumeSize:
    Type: String
    Default: 8
  SSHAccessSourceIP:
    Type: String
    Default: 0.0.0.0/0

Resources:
# ------------------------------------------------------------#
# IAM Role for EC2
# ------------------------------------------------------------#
  EC2IAMRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub ${PJPrefix}-${EC2InstanceName}-IAMRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
  
  EC2InstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: 
        - Ref: EC2IAMRole
      InstanceProfileName: !Sub ${PJPrefix}-${EC2InstanceName}-InstanceProfile

# ------------------------------------------------------------#
#  EC2Instance AZ:A
# ------------------------------------------------------------#
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #DependsOn: ManagedSecurityGroup
      #DeletionPolicy: Delete
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-${EC2InstanceName}-01

      # コンピューティング性能
      #
      # AMI
      ImageId: !Ref EC2InstanceAMI
      # インスタンスタイプ
      InstanceType: !Ref EC2InstanceInstanceType

      # キーペアの名前
      KeyName: !Ref KeyPairName
      # インスタンスを起動するサブネット
      SubnetId: { "Fn::ImportValue": !Sub "${CompanyPrefix}-private-subnet-a" }
      #
      IamInstanceProfile: !Ref EC2InstanceProfile
      # 終了保護（インスタンスの休止が有効であるかどうか）
      HibernationOptions: 
        Configured: false
      # 詳細モニタリングを有効にするかどうか
      Monitoring: false
      # インスタンスのテナンシー
      Tenancy: 'default'
      # インスタンスのアベイラビリティーゾーン
      AvailabilityZone: !Sub ${AWS::Region}a
      # セキュリティグループ
      SecurityGroupIds:
        - !Ref ManagedSecurityGroup
        - !Ref WebSecurityGroup
      #
      DisableApiTermination: false
      # VPC で起動されたインスタンスが NAT を実行できるようにするかどうか（隠しパラメータ）
      SourceDestCheck: true
      
      # EBS
      #
      # Amazon EBS I/O 用に最適化されているかどうか（隠しパラメータ） ※追加料金が発生しなければ最適化する価値があるかも
      EbsOptimized: false
      BlockDeviceMappings: 
        - DeviceName: /dev/xvda
          # ルートボリューム
          Ebs: 
            # ボリュームを暗号化するかどうか
            Encrypted: false
            # インスタンス終了時に EBS ボリュームを削除するかどうか
            DeleteOnTermination: true
            # ボリュームタイプ
            VolumeType: !Ref EC2InstanceVolumeType
            # ボリュームのサイズ（GiB 単位）
            VolumeSize: !Ref EC2InstanceVolumeSize
      #
      UserData: !Base64 | 
        #! /bin/bash
        yum update -y

# ------------------------------------------------------------#
#  SecurityGroup for Managed
# ------------------------------------------------------------#
  ManagedSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-managed-sg
      VpcId: { "Fn::ImportValue": !Sub "${CompanyPrefix}-vpc" }
      GroupName: !Sub ${PJPrefix}-managed-sg
      GroupDescription: "-"

      # Rule
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHAccessSourceIP
      SecurityGroupEgress: 
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

# ------------------------------------------------------------#
#  SecurityGroup for Web
# ------------------------------------------------------------#
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-web-sg
      VpcId: { "Fn::ImportValue": !Sub "${CompanyPrefix}-vpc" }
      GroupName: !Sub ${PJPrefix}-web-sg
      GroupDescription: "-"

  # Rule
  #WebSecurityGroupIngress: 
  #  Type: "AWS::EC2::SecurityGroupIngress"
  #  Properties: 
  #    IpProtocol: tcp
  #    FromPort: 80
  #    ToPort: 80
  #    SourceSecurityGroupId: !GetAtt [ GroupId ]
  #    GroupId: !GetAtt [ WebSecurityGroup, GroupId ]

# ------------------------------------------------------------#
# コンソール出力情報
# ------------------------------------------------------------#
Outputs:
  EC2Instance:
    Description: "-"
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${PJPrefix}-${EC2InstanceName}-01
  ManagedSecurityGroup:
    Description: "-"
    Value: !Ref ManagedSecurityGroup
    Export:
      Name: !Sub ${PJPrefix}-managed-sg
  WebSecurityGroup:
    Description: "-"
    Value: !Ref WebSecurityGroup
    Export:
      Name: !Sub ${PJPrefix}-web-sg
